# Copyright 2018 The Kubernetes Authors.

# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at

# http://www.apache.org/licenses/LICENSE-2.0

# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
---
- name: Install libseccomp package
  yum:
    name: libseccomp
    state: present
    lock_timeout: 60

- name: Configure nvidia driver repository
  shell: |
    curl -s -L https://developer.download.nvidia.com/compute/cuda/repos/rhel8/x86_64/cuda-rhel8.repo | \
    sudo tee /etc/yum.repos.d/cuda-rhel8.repo
  when: ansible_architecture == "x86_64" and gpu_provider == "nvidia"

- name: Configure nvidia driver repository
  shell: |
    curl -s -L https://developer.download.nvidia.com/compute/cuda/repos/rhel8/sbsa/cuda-rhel8.repo | \
    sudo tee /etc/yum.repos.d/cuda-rhel8.repo
  when: ansible_architecture == "aarch64" and gpu_provider == "nvidia"

- name: Obtain kernel version
  command: "uname -r"
  register: kernel_version_result
  when: gpu_provider == "nvidia"

- name: Configure kernel version
  set_fact:
    kernel_version: "{{ kernel_version_result.stdout }}"
  when: gpu_provider == "nvidia"

- name: Install kernel-devel and kernel-headers
  yum:
    name: "{{ item }}"
    state: present
  with_items:
    - kernel-devel-{{ kernel_version }}
    - kernel-headers-{{ kernel_version }}
  when: gpu_provider == "nvidia"

- name: Install NVIDIA Driver module
  command: dnf module install -y nvidia-driver
  when: gpu_provider == "nvidia"

- name: Configure nvidia container toolkit repository
  shell: |
    curl -s -L https://nvidia.github.io/libnvidia-container/stable/rpm/nvidia-container-toolkit.repo | \
    sudo tee /etc/yum.repos.d/nvidia-container-toolkit.repo
  when: gpu_provider == "nvidia"

- name: Install nvidia-container-toolkit package
  yum:
    name: nvidia-container-toolkit
    state: present
  when: gpu_provider == "nvidia"
