---
- name: Install libseccomp2 package
  apt:
    name: libseccomp2
    state: present

- name: Configure nvidia driver repository
  shell: |
    wget https://developer.download.nvidia.com/compute/cuda/repos/ubuntu2204/x86_64/cuda-keyring_1.1-1_all.deb && \
    sudo dpkg -i cuda-keyring_1.1-1_all.deb
  when: ansible_architecture == "x86_64"

- name: Configure nvidia driver repository
  shell: |
    wget https://developer.download.nvidia.com/compute/cuda/repos/ubuntu2204/sbsa/cuda-keyring_1.1-1_all.deb && \
    sudo dpkg -i cuda-keyring_1.1-1_all.deb
  when: ansible_architecture == "aarch64"

- name: Install nvidia packages
  apt:
    name: "{{ item }}"
    state: present
    update_cache: yes
  with_items:
    - nvidia-open-{{ nvidia_version }}

- name: Install dkms
  apt:
    name: "{{ item }}"
    state: present
    update_cache: yes
  with_items:
    - dkms

- name: Try to relocate the PCI devices for full GPU passthrough
  lineinfile:
    path: /etc/default/grub
    regexp: '^GRUB_CMDLINE_LINUX="(.*)"'
    line: 'GRUB_CMDLINE_LINUX="\1 pci=nocrs,realloc"'
    backrefs: yes

- name: Updating grub
  command: update-grub

- name: Set chosen CUDA and nccl vars
  set_fact:
    chosen_cuda: "{{ version_map[nvidia_version].cuda }}"
    chosen_libnccl: "{{ version_map[nvidia_version].libnccl2 }}"

- name: Configure nvidia container toolkit repository
  shell: |
    curl -fsSL https://nvidia.github.io/libnvidia-container/gpgkey | sudo gpg --dearmor -o /usr/share/keyrings/nvidia-container-toolkit-keyring.gpg \
      && curl -s -L https://nvidia.github.io/libnvidia-container/stable/deb/nvidia-container-toolkit.list | \
        sed 's#deb https://#deb [signed-by=/usr/share/keyrings/nvidia-container-toolkit-keyring.gpg] https://#g' | \
        sudo tee /etc/apt/sources.list.d/nvidia-container-toolkit.list

- name: Install nvidia-container-toolkit package
  apt:
    name: nvidia-container-toolkit
    update_cache: yes

- name: Install CUDA Toolkit
  apt:
    name:
      - cuda-toolkit-{{ chosen_cuda }}
      - libnccl2={{ chosen_libnccl}}
      - libnccl-dev={{ chosen_libnccl }}
      - libpci-dev
      - nvidia-hpc-benchmarks-openmpi
      - libnvshmem3-cuda-{{ version_map[nvidia_version].cuda_major }}
      - libnvshmem3-dev-cuda-{{ version_map[nvidia_version].cuda_major }}
      - python3-pip
      - build-essential
      - devscripts
      - debhelper
      - fakeroot
      - pkg-config
    state: present
    update_cache: yes
  when: nvidia_full_pack | bool

- name: Install NVSHMEM language bidings for Python
  pip:
    name: nvshmem4py-cu{{ version_map[nvidia_version].cuda_major }}
    break_system_packages: true
    state: present
    executable: pip3
  when: nvidia_full_pack | bool

- name: Clone NVIDIA gdrcopy repository
  ansible.builtin.git:
    repo: https://github.com/NVIDIA/gdrcopy.git
    dest: /tmp/gdrcopy
    version: master
  when:
    - nvidia_full_pack | bool

- name: Build gdrcopy Debian packages
  ansible.builtin.shell:
    cmd: CUDA=/usr/local/cuda ./build-deb-packages.sh
    chdir: /tmp/gdrcopy/packages
  when:
    - nvidia_full_pack | bool

- name: Install gdrcopy Debian packages
  ansible.builtin.apt:
    deb: "/tmp/gdrcopy/packages/{{ item }}"
    state: present
  loop:
    - "gdrdrv-dkms_{{ gdrcopy_version }}_{{ 'amd64' if ansible_architecture == 'x86_64' else 'arm64' }}.Ubuntu22_04.deb"
    - "libgdrapi_{{ gdrcopy_version }}_{{ 'amd64' if ansible_architecture == 'x86_64' else 'arm64' }}.Ubuntu22_04.deb"
    - "gdrcopy-tests_{{ gdrcopy_version }}_{{ 'amd64' if ansible_architecture == 'x86_64' else 'arm64' }}.Ubuntu22_04+cuda{{ cuda_minor }}.deb"
    - "gdrcopy_{{ gdrcopy_version }}_{{ 'amd64' if ansible_architecture == 'x86_64' else 'arm64' }}.Ubuntu22_04.deb"
  vars:
    cuda_minor: "{{ version_map[nvidia_version].cuda_minor }}"
  when:
    - nvidia_full_pack | bool

- name: Disable UFW service
  systemd:
    name: ufw
    enabled: no
    state: stopped
  when: nvidia_full_pack | bool

- name: Enable NVIDIA persistenced service
  systemd:
    name: nvidia-persistenced
    enabled: yes
  when: nvidia_full_pack | bool
  ignore_errors: yes

- name: Create GRUB configuration for NVIDIA DRM
  copy:
    content: 'GRUB_CMDLINE_LINUX_DEFAULT="$GRUB_CMDLINE_LINUX_DEFAULT nvidia-drm.modeset=0"'
    dest: /etc/default/grub.d/99-hyperplane.cfg
    mode: '0644'
  when: nvidia_full_pack | bool

- name: Create NVIDIA peermem module configuration
  copy:
    content: 'nvidia-peermem'
    dest: /etc/modules-load.d/nvidia-peermem.conf
    mode: '0644'
  when: nvidia_full_pack | bool

- name: Update initramfs and GRUB
  command:
    cmd: "{{ item }}"
  loop:
    - update-initramfs -u -k all
    - update-grub
  when: nvidia_full_pack | bool

- name: Remove temp files
  file:
    state: absent
    path: "{{ item.path }}"
  loop:
  - { path: /root/cuda-keyring_1.1-1_all.deb }
  - { path: "/home/{{ ansible_env.SUDO_USER }}/cuda-keyring_1.1-1_all.deb" }
