---
- name: Install base packages (minimal)
  apt:
    name:
      - libseccomp2
      - curl
      - ca-certificates
      - gnupg
      - pciutils
    state: present
    update_cache: yes

- name: Disable nouveau
  copy:
    dest: /etc/modprobe.d/blacklist-nouveau.conf
    mode: "0644"
    content: |
      blacklist nouveau
      options nouveau modeset=0

- name: Try to relocate the PCI devices for full GPU passthrough
  lineinfile:
    path: /etc/default/grub
    regexp: '^GRUB_CMDLINE_LINUX="(.*)"'
    line: 'GRUB_CMDLINE_LINUX="\1 pci=nocrs,realloc"'
    backrefs: yes

- name: Disable UFW service
  systemd:
    name: ufw
    enabled: no
    state: stopped

- name: Ensure nouveau is not loaded in initramfs
  command: update-initramfs -u -k all
  changed_when: true

- name: Create GRUB configuration for NVIDIA DRM
  copy:
    content: 'GRUB_CMDLINE_LINUX_DEFAULT="$GRUB_CMDLINE_LINUX_DEFAULT nvidia-drm.modeset=0"'
    dest: /etc/default/grub.d/99-hyperplane.cfg
    mode: '0644'

- name: Updating grub
  command: update-grub
