- name: Clone pre-built lustre repository
  git:
    repo: "{{ lustre_repo }}"
    dest: /tmp/prebuilt-lustre
    version: main

- name: Debug current kernel version
  debug:
    msg: "Current kernel version is {{ ansible_kernel }}"

- name: Install specific kernel image and headers
  apt:
    name:
      - "linux-image-{{ ansible_kernel }}"
      - "linux-headers-{{ ansible_kernel }}"
    state: present
  register: kernel_install

- name: Install equivs tool
  apt:
    name: equivs
    state: present

- name: Create control file for linux-image dummy
  copy:
    dest: /tmp/linux-image-equivs.control
    content: |
      Section: misc
      Priority: optional
      Standards-Version: 3.9.2
      Package: linux-image
      Version: {{ dummy_version }}
      Architecture: all
      Provides: linux-image
      Description: Dummy linux-image package to satisfy Lustre DKMS dependency

- name: Build linux-image dummy package
  command: equivs-build /tmp/linux-image-equivs.control
  args:
    chdir: /tmp

- name: Install linux-image dummy package
  apt:
    deb: /tmp/linux-image_{{ dummy_version }}_all.deb
    state: present

- name: Create & build linux-image-generic dummy
  block:
    - copy:
        dest: /tmp/linux-image-generic-equivs.control
        content: |
          Section: misc
          Priority: optional
          Standards-Version: 3.9.2
          Package: linux-image-generic
          Version: {{ dummy_version }}
          Architecture: all
          Provides: linux-image-generic
          Description: Dummy linux-image-generic package to satisfy Lustre DKMS dependency
    - command: equivs-build /tmp/linux-image-generic-equivs.control
      args:
        chdir: /tmp
    - apt:
        deb: /tmp/linux-image-generic_{{ dummy_version }}_all.deb
        state: present

- name: Clean up temporary control files
  file:
    path: /tmp/linux-image*-equivs.control
    state: absent

- name: Hold the installed kernel packages
  shell: |
    apt-mark hold linux-image-{{ ansible_kernel }} \
                 linux-headers-{{ ansible_kernel }}
  when: kernel_install.changed

- name: Install lustre dependencies
  apt:
    name: "{{ item }}"
    state: present
    update_cache: yes
  with_items:
  - libjson-c-dev
  - libyaml-dev

- name: Find lustre dkms module deb files in /tmp folder
  find:
    name: "/tmp/prebuilt-lustre/{{ ansible_distribution }}/{{ ansible_architecture }}/"
    patterns: "lustre-client-modules-dkms_*.deb"
  register: dkms_deb_files

- name: Setting lustre dkms_deb_list
  set_fact:
    dkms_deb_list: "{{ dkms_deb_files.files | map(attribute='path') | list}}"

- name: Install lustre dkms deb package
  apt:
    deb: "{{ item }}"
    state: present
    update_cache: yes
  with_items: "{{ dkms_deb_list }}"

- name: Find lustre client utils deb files in /tmp folder
  find:
    name: "/tmp/prebuilt-lustre/{{ ansible_distribution }}/{{ ansible_architecture }}/"
    patterns: "lustre-client-utils_*.deb"
  register: utils_deb_files

- name: Setting lustre utils_deb_list
  set_fact:
    utils_deb_list: "{{ utils_deb_files.files | map(attribute='path') | list}}"

- name: Install lustre client utils deb package
  apt:
    deb: "{{ item }}"
    state: present
    update_cache: yes
  with_items: "{{ utils_deb_list }}"

- name: Find lustre userspace deb files in /tmp folder
  find:
    name: "/tmp/prebuilt-lustre/{{ ansible_distribution }}/{{ ansible_architecture }}/"
    patterns: "*.deb"
    excludes:
      - "lustre-client-modules-dkms_*.deb"
      - "lustre-client-utils_*.deb"
  register: deb_files

- name: Setting lustre userspace deb_list
  set_fact:
    deb_list: "{{ deb_files.files | map(attribute='path') | list}}"

- name: Install lustre client deb packages
  apt:
    deb: "{{ item }}"
    state: present
    update_cache: yes
  with_items: "{{ deb_list }}"

- name: Remove pre-built lustre directory
  file:
    path: /tmp/prebuilt-lustre
    state: absent
