- name: Install archive/extraction tools
  dnf:
    name:
      - tar
      - gzip
      - bzip2
      - unzip
    state: present

- name: Install dependencies for DOCA
  dnf:
    name:
      - which
    state: present
