---
  - block:
    - name: Install OVS dependencies
      apt:
        name: [ 'git' ]
        state: present

    - name: Clone pre-built OVS repository
      git:
        repo: "{{ ovs_repo }}"
        dest: "{{ tmp_path }}/prebuilt-ovs"
        version: "{{ ovs_deb_version }}"

    - name: Find all dkms module deb files in /tmp folder
      find:
        name: "{{ tmp_path }}/prebuilt-ovs/{{ ansible_distribution }}-{{ ansible_distribution_version }}/{{ ansible_architecture }}/"
        patterns: "openvswitch-datapath-dkms_*.deb"
      register: dkms_deb_files

    - name: Setting dkms_deb_list
      set_fact:
        dkms_deb_list: "{{ dkms_deb_files.files | map(attribute='path') | list}}"

    - name: Remove default openvswitch module
      file:
        path: "/lib/modules/{{ ansible_kernel }}/kernel/net/openvswitch"
        state: absent        

    - name: Install OVS dataplane dkms deb package
      apt:
        deb: "{{ item }}"
        state: present
        update_cache: yes
      with_items: "{{ dkms_deb_list }}"

    - name: Remove pre-built OVS directory
      file:
        path: "{{ tmp_path }}/prebuilt-ovs"
        state: absent
