---
  - block:
    - name: Install IPVS package
      yum:
        name: ipvsadm
        state: present

    - name: Touch ipvsadm rule file
      file:
        path: /etc/sysconfig/ipvsadm
        state: touch
        mode: u=rw,g=r,o=r

    - name: Start and enable ipvsadm daemon
      service:
        name: ipvsadm
        state: started
        enabled: yes
