---
  - block:
    - name: Install OVS dependencies
      yum:
        name: ['git', 'net-tools', 'libibverbs']
        state: present

    - name: Clone pre-built OVS repository
      git:
        repo: "{{ ovs_repo }}"
        dest: "{{ tmp_path }}/prebuilt-ovs"
        version: "{{ ovs_el_version }}"

    - name: ovs_install | Obtain kernel version
      command: "uname -r"
      register: kernel_version_result

    - name: ovs_install | Configure kernel version
      set_fact:
        kernel_version: "{{ kernel_version_result.stdout }}"

    - name: Find all kernel module rpm files in /tmp folder
      find:
        name: "{{ tmp_path }}/prebuilt-ovs/{{ ansible_distribution }}-{{ ansible_distribution_major_version }}/{{ ansible_architecture }}/kmod/{{ kernel_version }}/"
        patterns: "*.rpm"
      register: kmod_rpm_files

    - name: Setting rpm_kmod_list
      set_fact:
        kmod_rpm_list: "{{ kmod_rpm_files.files | map(attribute='path') | list}}"

    - name: Install OVS kernel modules
      yum:
        name: "{{ kmod_rpm_list }}"
        state: present
        disable_gpg_check: yes

    - name: Remove pre-built OVS directory
      file:
        path: "{{ tmp_path }}/prebuilt-ovs"
        state: absent
