---
  - block:
    - include_tasks: el_ovs.yml
      when: ansible_os_family == "RedHat" and ansible_distribution_major_version == "8"

    - include_tasks: deb_ovs.yml
      when: ansible_distribution == "Ubuntu" and ansible_distribution_version == "20.04"

    - include_tasks: el_ipvs.yml
      when: ansible_os_family == "RedHat"

    - include_tasks: deb_ipvs.yml
      when: ansible_os_family == "Debian" or ansible_os_family == "Ubuntu"

    - name: Enable kernel modules
      template:
        src: templates/module.conf.j2
        dest: "/etc/modules-load.d/{{ item.name }}.conf"
      with_items:
      - { name: 'vxlan', kernel_module: 'vxlan' }
      - { name: 'geneve', kernel_module: 'geneve' }
      - { name: 'gre', kernel_module: 'gre' }
      - { name: 'vport_vxlan', kernel_module: 'vport_vxlan' }
      - { name: 'vport_geneve', kernel_module: 'vport_geneve' }
      - { name: 'vport_gre', kernel_module: 'vport_gre' }
      - { name: 'vport_stt', kernel_module: 'vport_stt' }
      - { name: 'openvswitch', kernel_module: 'openvswitch' }

    - name: Enable ipvs modules
      template:
        src: templates/module.conf.j2
        dest: "/etc/modules-load.d/{{ item.name }}.conf"
      with_items:
      - { name: 'ip_vs', kernel_module: 'ip_vs' }
      - { name: 'ip_vs_rr', kernel_module: 'ip_vs_rr' }
      - { name: 'ip_vs_wrr', kernel_module: 'ip_vs_wrr' }
      - { name: 'ip_vs_sh', kernel_module: 'ip_vs_sh' }
