---
  - block:
    - include_tasks: el_ipvs.yml
      when: ansible_os_family == "RedHat"

    - include_tasks: deb_ipvs.yml
      when: ansible_os_family == "Debian"

    - name: Enable kernel modules
      template:
        src: templates/module.conf.j2
        dest: "/etc/modules-load.d/{{ item.name }}.conf"
      with_items:
      - { name: 'vxlan', kernel_module: 'vxlan' }
      - { name: 'geneve', kernel_module: 'geneve' }

    - name: Enable ipvs modules
      template:
        src: templates/module.conf.j2
        dest: "/etc/modules-load.d/{{ item.name }}.conf"
      with_items:
      - { name: 'ip_vs', kernel_module: 'ip_vs' }
      - { name: 'ip_vs_rr', kernel_module: 'ip_vs_rr' }
      - { name: 'ip_vs_wrr', kernel_module: 'ip_vs_wrr' }
      - { name: 'ip_vs_sh', kernel_module: 'ip_vs_sh' }
