---
- name: Download rebellions driver
  get_url:
    url: https://axxcz8fkeabo.objectstorage.ap-singapore-2.oci.customer-oci.com/p/xKcWqpnTUHAGkZFWkw0Ox5F2keFSiw16xYxPCozwGMjkl28pkz85TV4Q1MM7LavD/n/axxcz8fkeabo/b/rebellions/o/atom_external_release_16gbps_1.3.73_amd64.deb
    dest: /opt/rebellions/rebellions_driver.deb
    mode: 0644

- name: Install dkms
  apt:
    name: "{{ item }}"
    state: present
    update_cache: yes
  with_items:
    - dkms

- name: Copy rebellions install service
  copy:
    src: etc/systemd/system/rbln-install-deb.service
    dest: /etc/systemd/system/rbln-install.service
    owner: root
    group: root
    mode: '0644'
