---
- name: Download rebellions driver
  get_url:
    url: https://axxcz8fkeabo.objectstorage.ap-singapore-2.oci.customer-oci.com/p/Leru06kp5KGp_QiPNkqhcdRjoDqyfYXBYQyJv7_g8KqJtg7FNOsDKu3ZkEEhfBNC/n/axxcz8fkeabo/b/rebellions/o/atom_external_release_16gbps_1.3.80-2.x86_64.rpm
    dest: /opt/rebellions/rebellions_driver.rpm
    mode: 0644

- name: Install epel-release
  dnf:
    name: "{{ item }}"
    state: present
  with_items:
    - epel-release

- name: Update packages
  command: dnf update -y
  become: true

- name: Copy rebellions install service
  copy:
    src: etc/systemd/system/rbln-install-rpm.service
    dest: /etc/systemd/system/rbln-install.service
    owner: root
    group: root
    mode: '0644'
