---
  - block:
  
    - include_tasks: el_security.yml
      when: ansible_os_family == "RedHat"

    - include_tasks: deb_security.yml
      when: ansible_os_family == "Debian"

    - name: Change the shadow file permission
      file:
        path: /etc/shadow
        mode: '0400'

    - name: Change SU file permission
      file:
        path: /bin/su
        mode: '4750'

    - name: Add umask in profile
      lineinfile:
        dest: /etc/profile
        insertafter: EOF
        line: "umask 022"

    - name: Configure session timeout value to 3600
      lineinfile:
        dest: /etc/profile
        insertafter: EOF
        line: "{{ item }}"
      with_items:
        - TMOUT=3600
        - export TMOUT
        
    - name: Create hosts.equiv file
      copy:
        content: ""
        dest: "{{ item }}"
        group: root
        owner: root
        mode: 000
      with_items:
        - /etc/hosts.equiv
        - /root/.rhosts

    - name: Do not permit Root login with password
      lineinfile:
        dest: /etc/ssh/sshd_config
        regexp: '#PermitRootLogin prohibit-password'
        line: 'PermitRootLogin no'

    - name: Do not permit empty password authentication
      lineinfile:
        dest: /etc/ssh/sshd_config
        regexp: '#PermitEmptyPasswords no'
        line: 'PermitEmptyPasswords no'

    - name: Enlarge the log rotate duration to 12 weeks
      replace:
        path: /etc/logrotate.conf
        regexp: 'rotate 4'
        replace: 'rotate 12'
