version_map:
  "560":
    cuda: "12-6"
    cuda_major: "12"
    cuda_minor: "12.6"
    libnccl2: "2.24.3-1+cuda12.6"
    nccl_test: "tags/v2.16.7"
  "570":
    cuda: "12-8"
    cuda_major: "12"
    cuda_minor: "12.8"
    libnccl2: "2.26.2-1+cuda12.8"
    nccl_test: "tags/v2.16.7"
  "575":
    cuda: "12-9"
    cuda_major: "12"
    cuda_minor: "12.9"
    libnccl2: "2.27.7-1+cuda12.9"
    nccl_test: "tags/v2.16.7"
  "580":
    cuda: "13-0"
    cuda_major: "13"
    cuda_minor: "13.0"
    libnccl2: "2.28.3-1+cuda13.0"
    nccl_test: "master"
